spring:
  application:
    name: course_snap_backend
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.153.170.199:3306/course_snap?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: course_snap
    password: 1234..
#    url: jdbc:mysql://localhost:3306/course_snap?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: 1234
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启了驼峰命名的开关
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*.xml #指定mapper.xml文件的位置
imgae:
  base-url: D:/CourseSnap/photo/
  photo-url: http://localhost:8080/photo/